# Site settings
title: Dave Allen Graphics
email: mrdavidrobertallen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Graphic design and website design, Huddersfield
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: additionaldave
github_username:  vimallen

# Build settings
markdown: kramdown
sass:
 style: compressed